// var x=prompt("What is your name?","name");
// var h1=document.getElementById("h1").innerHTML=x;
// var x=prompt("Enter any Number");
// console.log(typeof(x));
// x=Number(x);
// console.log(typeof(x));
// x=x.toString();
// console.log(typeof(x));
var a=21.378098/7;
console.log(a);
a=a.toFixed(2);
console.log(a);
//Frist name
var Fristname=prompt("What is your Frist name?");
console.log("Frist name : ",Fristname);
document.write("Frist name :",Fristname);
document.write("<br />");
var Lastname=prompt("What is your last name?");
console.log("last name : ",Lastname);
document.write("last name :",Lastname);
document.write("<br />");
var Fathername=prompt("What is your Father name?");
console.log("Fathername : ",Fathername);
document.write("Fathername :",Fathername);
document.write("<br />");
var Gender=prompt("What is your Gender?");
console.log("Gender : ",Gender);
document.write("Gender :",Gender);
document.write("<br />");
var MobileNumber=prompt("What is your MobileNumber?");
console.log("MobileNumber : ",MobileNumber);
document.write("MobileNumber :",MobileNumber);
document.write("<br />");
var Address=prompt("What is your Address?");
console.log("Address : ",Address);
document.write("Address :",Address);
document.write("<br />");
var CNICNO=prompt("What is your CNIC NO?");
console.log("CNIC NO : ",CNICNO);
document.write("CNIC NO :",CNICNO);
document.write("<br />");
var Lastname=prompt("What is your ?");
console.log("last name : ",Lastname);
document.write("last name :",Lastname);